# Generated by Django 4.1 on 2022-09-05 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='users',
            new_name='user',
        ),
    ]
